Error: ER_NO_SUCH_TABLE: Table 's281656_items.file' doesn't exist
    at Query.Sequence._packetToError (/home/s281656/nodevenv/api_clon_drive/16/lib/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/home/s281656/nodevenv/api_clon_drive/16/lib/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/home/s281656/nodevenv/api_clon_drive/16/lib/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/s281656/nodevenv/api_clon_drive/16/lib/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/s281656/nodevenv/api_clon_drive/16/lib/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/home/s281656/nodevenv/api_clon_drive/16/lib/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/home/s281656/nodevenv/api_clon_drive/16/lib/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/home/s281656/nodevenv/api_clon_drive/16/lib/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    --------------------
    at Protocol._enqueue (/home/s281656/nodevenv/api_clon_drive/16/lib/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/home/s281656/nodevenv/api_clon_drive/16/lib/node_modules/mysql/lib/Connection.js:198:25)
    at /home/s281656/api_clon_drive/src/database/Files.js:20:16
    at new Promise (<anonymous>)
    at Object.getFilesByUserIdAndParentId (/home/s281656/api_clon_drive/src/database/Files.js:19:10)
    at Object.getFilesByUserIdAndParentId (/home/s281656/api_clon_drive/src/services/fileService.js:26:18)
    at getFilesByUserIdAndParentId (/home/s281656/api_clon_drive/src/controllers/fileController.js:46:37)
    at Layer.handle [as handle_request] (/home/s281656/nodevenv/api_clon_drive/16/lib/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/s281656/nodevenv/api_clon_drive/16/lib/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/home/s281656/nodevenv/api_clon_drive/16/lib/node_modules/express/lib/router/route.js:114:3) {
  code: 'ER_NO_SUCH_TABLE',
  errno: 1146,
  sqlMessage: "Table 's281656_items.file' doesn't exist",
  sqlState: '42S02',
  index: 0,
  sql: "SELECT * FROM file WHERE userId = 'ofiEtu05VYR9vtCyktCXVeD7tWL2' AND parentId = 'ofiEtu05VYR9vtCyktCXVeD7tWL2'"
}
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: Packets out of order. Got: 0 Expected: 3
    at Parser._tryReadPacketHeader (/home/s281656/nodevenv/api_clon_drive/16/lib/node_modules/mysql/lib/protocol/Parser.js:470:15)
    at Parser.write (/home/s281656/nodevenv/api_clon_drive/16/lib/node_modules/mysql/lib/protocol/Parser.js:33:29)
    at Protocol.write (/home/s281656/nodevenv/api_clon_drive/16/lib/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/home/s281656/nodevenv/api_clon_drive/16/lib/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/home/s281656/nodevenv/api_clon_drive/16/lib/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
Emitted 'error' event on Connection instance at:
    at Connection._handleProtocolError (/home/s281656/nodevenv/api_clon_drive/16/lib/node_modules/mysql/lib/Connection.js:423:8)
    at Protocol.emit (node:events:513:28)
    at Protocol._delegateError (/home/s281656/nodevenv/api_clon_drive/16/lib/node_modules/mysql/lib/protocol/Protocol.js:398:10)
    at Protocol.handleParserError (/home/s281656/nodevenv/api_clon_drive/16/lib/node_modules/mysql/lib/protocol/Protocol.js:380:10)
    at Parser._tryReadPacketHeader (/home/s281656/nodevenv/api_clon_drive/16/lib/node_modules/mysql/lib/protocol/Parser.js:478:10)
    at Parser.write (/home/s281656/nodevenv/api_clon_drive/16/lib/node_modules/mysql/lib/protocol/Parser.js:33:29)
    [... lines matching original stack trace ...]
    at Socket.emit (node:events:513:28) {
  code: 'PROTOCOL_PACKETS_OUT_OF_ORDER',
  fatal: true
}
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: Packets out of order. Got: 0 Expected: 2
    at Parser._tryReadPacketHeader (/home/s281656/nodevenv/api_clon_drive/16/lib/node_modules/mysql/lib/protocol/Parser.js:470:15)
    at Parser.write (/home/s281656/nodevenv/api_clon_drive/16/lib/node_modules/mysql/lib/protocol/Parser.js:33:29)
    at Protocol.write (/home/s281656/nodevenv/api_clon_drive/16/lib/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/home/s281656/nodevenv/api_clon_drive/16/lib/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/home/s281656/nodevenv/api_clon_drive/16/lib/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
Emitted 'error' event on Connection instance at:
    at Connection._handleProtocolError (/home/s281656/nodevenv/api_clon_drive/16/lib/node_modules/mysql/lib/Connection.js:423:8)
    at Protocol.emit (node:events:513:28)
    at Protocol._delegateError (/home/s281656/nodevenv/api_clon_drive/16/lib/node_modules/mysql/lib/protocol/Protocol.js:398:10)
    at Protocol.handleParserError (/home/s281656/nodevenv/api_clon_drive/16/lib/node_modules/mysql/lib/protocol/Protocol.js:380:10)
    at Parser._tryReadPacketHeader (/home/s281656/nodevenv/api_clon_drive/16/lib/node_modules/mysql/lib/protocol/Parser.js:478:10)
    at Parser.write (/home/s281656/nodevenv/api_clon_drive/16/lib/node_modules/mysql/lib/protocol/Parser.js:33:29)
    [... lines matching original stack trace ...]
    at Socket.emit (node:events:513:28) {
  code: 'PROTOCOL_PACKETS_OUT_OF_ORDER',
  fatal: true
}
